// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_tempImage;
extern lv_obj_t * ui_rhumImage;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_rhumLabel;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_tempChart;
extern lv_obj_t * ui_tempLabel2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_temp_small_png);    // assets/temp_small.png
LV_IMG_DECLARE(ui_img_rhum_small_png);    // assets/rhum_small.png


LV_FONT_DECLARE(ui_font_Font1);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif