// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x85888C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rhumChart1 = lv_chart_create(ui_Screen3);
    lv_obj_set_width(ui_rhumChart1, 195);
    lv_obj_set_height(ui_rhumChart1, 80);
    lv_obj_set_x(ui_rhumChart1, -5);
    lv_obj_set_y(ui_rhumChart1, 0);
    lv_obj_set_align(ui_rhumChart1, LV_ALIGN_RIGHT_MID);
    lv_chart_set_type(ui_rhumChart1, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_rhumChart1, LV_CHART_AXIS_PRIMARY_Y, 0, 1000);
    lv_chart_set_range(ui_rhumChart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_rhumChart1, 5, 10);
    lv_chart_set_axis_tick(ui_rhumChart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_rhumChart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 3, true, 50);
    lv_chart_set_axis_tick(ui_rhumChart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);

    lv_obj_set_style_line_color(ui_rhumChart1, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_rhumChart1, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_rhumChart1, 3, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_rhumChart1, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rhumChart1, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_rhumLabel1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_rhumLabel1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_rhumLabel1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_rhumLabel1, 0);
    lv_obj_set_y(ui_rhumLabel1, -2);
    lv_obj_set_align(ui_rhumLabel1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_rhumLabel1, "Luchtvochtigheid");
    lv_obj_set_style_text_color(ui_rhumLabel1, lv_color_hex(0x0C52D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rhumLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rhumLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
}