// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x85888C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_tempImage, &ui_img_temp_small_png);
    lv_obj_set_width(ui_tempImage, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tempImage, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tempImage, 12);
    lv_obj_set_y(ui_tempImage, 2);
    lv_obj_add_flag(ui_tempImage, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_tempImage, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_rhumImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_rhumImage, &ui_img_rhum_small_png);
    lv_obj_set_width(ui_rhumImage, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_rhumImage, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_rhumImage, -4);
    lv_obj_set_y(ui_rhumImage, 0);
    lv_obj_set_align(ui_rhumImage, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_rhumImage, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_rhumImage, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_tempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tempLabel, 10);
    lv_obj_set_y(ui_tempLabel, 20);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_tempLabel, "00.0 C");
    lv_obj_set_style_text_color(ui_tempLabel, lv_color_hex(0xFF4C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_tempLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_tempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rhumLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rhumLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_rhumLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_rhumLabel, 10);
    lv_obj_set_y(ui_rhumLabel, 85);
    lv_obj_set_align(ui_rhumLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_rhumLabel, "00.0 %");
    lv_obj_set_style_text_color(ui_rhumLabel, lv_color_hex(0x0C52D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rhumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_rhumLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rhumLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rhumLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
}